import 'package:flutter/material.dart';

// TODO: This file will be generated by flutter gen-l10n
// For now, it's a placeholder.

class AppLocalizations {
  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  // Example getter for a localized string
  String get helloWorld => 'Hello World!';

  // Add more localized strings here
} 